name: clinical-trial-platform
description: MLOps project for clinical trial matching
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-python
