FROM apache/airflow:2.9.3

USER root
RUN apt-get update && apt-get install -y git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir "dvc==3.55.2" requests pandas
