import logging
from vertexai.language_models import TextEmbeddingModel, TextEmbeddingInput
import vertexai
import os

logger = logging.getLogger(__name__)

vertexai.init(
    project=os.getenv("GCP_PROJECT_ID"),
    location=os.getenv("GCP_REGION", "us-central1")
)

EMBEDDING_MODEL = "text-embedding-005"

def get_patient_embedding(text_summary: str) -> list[float]:
    """
    Takes a patient text summary and returns a vector embedding.

    Args:
        text_summary: Plain text summary of the patient profile
                      (generated by Patient.to_text_summary())

    Returns:
        List of floats representing the embedding vector (768 dimensions)
    """
    try:
        logger.info("Generating embedding for patient summary...")
        model = TextEmbeddingModel.from_pretrained(EMBEDDING_MODEL)

        # task_type is passed inside TextEmbeddingInput, not to get_embeddings()
        inputs = [TextEmbeddingInput(text=text_summary, task_type="RETRIEVAL_QUERY")]
        embeddings = model.get_embeddings(inputs)

        vector = embeddings[0].values
        logger.info(f"Embedding generated — dimensions: {len(vector)}")
        return vector

    except Exception as e:
        logger.error(f"Failed to generate embedding: {str(e)}")
        raise